title: Allef Gomes
description: > # this means to ignore newlines until "baseurl:"
  I am a software developer focusing in backend with ruby, elixir and nodejs but I have expiriencies with Angular2+, ReactJs, React-Native, Ionic and others techs.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Allef Gomes # add your name
author-img: allef-gomes.jpg # add your photo
about-author: Olá! Sou Allef Gomes, graduado em Sistemas para Internet e pós graduado em MBA em Engenharia de Software Ágil. Aqui pretendo escrever sobre meus aprendizados diários.
social-github: allefgomes
social-linkedin: allef-gomes
social-email: allefgalmeida@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
